working_dir: /home/david/Documents/projects/test_dp
num_parameters: 4
setup_file: /home/david/Documents/projects/dp/optimizer/setup.txt
std_rules: /home/david/Documents/projects/dp/optimizer/std_rules.xml
chemaxon: /home/david/opt/chemaxon/jchemsuite/bin
seed_structure: /home/david/Documents/projects/test_dp/phenylpiperizine.sdf
number_of_selected_compounds: 5
bounded_box: True
properties_chemaxon: charge logp acc don refractivity
properties_sirms: CHARGE LOGP HB REFRACTIVITY
properties_calc_contrib: overall
smart_string: '[#6+0;!$(*=,#[!#6])]!@!=!#[*]'
max_cuts: 3
radius: 3
replacement_database: /home/david/Documents/projects/dp/optimizer/replacement_chembl_cuts4_H.db
number_of_worst_fragments: 3
max_frag_size: 7
output_format: svm
num_of_generation: 1
optimization_methods: pareto desirability
store_all_files: True
param_0:
  name: 5HT1A
  path: /home/david/Documents/projects/dp/optimizer/models/5HT1A
  types_of_alg: rf svm gbm
  type_of_model: reg
  threshold: more7
  range: 10
  desirability: 7:0,9:(x-7)/2,100:1
param_1:
  name: BBB
  path: /home/david/Documents/projects/dp/optimizer/models/BBB
  types_of_alg: rf svm gbm
  type_of_model: class
  threshold: more0.5
  range: 1
  desirability: 0.5:0,0.8:(1/0.3)*x-(5/3),100:1
param_2:
  name: HIA
  path: /home/david/Documents/projects/dp/optimizer/models/HIA
  types_of_alg: rf svm gbm
  type_of_model: class
  threshold: more0.5
  range: 1
  desirability: 0.5:0,0.8:(1/0.3)*x-(5/3),100:1
param_3:
  name: HLM
  path: /home/david/Documents/projects/dp/optimizer/models/HLM
  types_of_alg: rf svm gbm
  type_of_model: class
  threshold: less0.5
  range: 1
  desirability: 0.2:1,0.5:-(1/0.3)*x+(5/3),100:0
